name: KiwiPerGroupDrops
main: nl.itz_kiwisap_.spigot.pergroupdrops.plugin.KiwiPerGroupDropsPlugin
version: ${per-group-drops.version}
author: Itz_KiwiSap_
api-version: 1.16

softdepend:
  - SuperiorSkyblock2